### ISSUE TITLE
Notion Table Link

### ISSUE THREAD

**Issue by JJKW1984** [spencerpauly/awesome-notion#5]
Might I suggest that we track this information in a public notion or airtable databse?
That would allow nontechnical people to add resources. 
I would happy to help coordinate and submit pull requests.

Thoughts?

**Comment by spencerpauly** [comment]
That's an interesting idea. How would multiple people be able to edit a notion page/airtable without being able to be malicious if they wanted to? Is there a way to have notion pages that need an approval process?
